name: Update Websites

on:
  # Schedule makes this bot run in regular intervals, without any interventions
  #schedule:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
      - name: Checkout Git
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Get pip cache dir
        id: pip-cache
        run: |
          echo "::set-output name=dir::$(pip cache dir)"

      - name: Cache python packages
        uses: actions/cache@v2
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: ${{ runner.os }}-pip-${{ hashFiles('./requirements.txt') }}

      - name: Install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r ./requirements.txt

      - name: Run python scripts
        env: 
          SHEET_TROOPS: ${{ secrets.SHEET_TROOPS }}
          SHEET_ASSESSMENTS: ${{ secrets.SHEET_ASSESSMENTS }}
        run: |
          python ./src/export_data.py

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "10"

      - name: Commit files
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "Autoupdate" -- ./data

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GIT_TOKEN }}
          #branch: ${{ github.ref }}
          
      - name: FTP Deploy to WP Engine (Production)
        uses: SamKirkland/FTP-Deploy-Action@3.1.1
        with:
          ftp-server:  ${{ secrets.FTP_HOST }}
          ftp-username: ${{ secrets.FTP_USERNAME }}
          ftp-password: ${{ secrets.FTP_PASSWORD }}
          local-dir: data
          git-ftp-args: --insecure   
