name: Sheets to Website

on:
  # Schedule makes this bot run in regular intervals, without any interventions
  #schedule:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Get pip cache dir
        id: pip-cache
        run: |
          echo "::set-output name=dir::$(pip cache dir)"
      - name: Cache python packages
        uses: actions/cache@v2
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: ${{ runner.os }}-pip-${{ hashFiles('./requirements.txt') }}
      - name: Install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r ./requirements.txt
      - name: Run python scripts
        run: |
          python ./src/export_data.py
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "10"

      - name: FTP Deploy to WP Engine (Production)
        # Doku: https://github.com/SamKirkland/FTP-Deploy-Action/tree/3.1.1
        uses: SamKirkland/FTP-Deploy-Action@3.1.1
        with:
          ftp-server:  ${{ secrets.FTP_HOST }}
          ftp-username: ${{ secrets.FTP_USERNAME }}
          ftp-password: ${{ secrets.FTP_PASSWORD }}
          local-dir: data
          git-ftp-args: --insecure          
        
      #- name: Log failure to slack
      #  if: always()
      #  uses: ravsamhq/notify-slack-action@v1
      #  with:
      #    status: ${{ job.status }}
      #    notify_when: "failure"
      #  env:
      #    SLACK_WEBHOOK_URL: ${{ secrets.ACTION_MONITORING_SLACK }}
